config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>hola desde edit.html</h1>

<h1>Edit Task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%# <%= form.text_area :body, size: "60x10" %><%# no necesito esto que me genera un cuadro para poner texto largo%>
  <%= form.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>Hola desde index.html.erb</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to "Create new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>hola desde new.html</h1>
<h1>New Task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%# <%= form.text_area :body, size: "60x10" %><%# no necesito esto que me genera un cuadro para poner texto largo%>
  <%= form.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1>hola desde show.html</h1>

<ul>
  <li><%= @task.id %></li>
  <li><%= @task.title %></li>
  <li><%= @task.details %></li>
</ul>

<%= link_to "Edit this task", edit_task_path(@task) %>
<br>
<%= link_to "Delete this task",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<br>
<%= link_to "Back to list", tasks_path %>